services:
  - type: web
    name: manga-recommender
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn -c gunicorn_config.py api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: manga-recommender-db
          property: connectionString
      - key: SECRET_KEY 
        generateValue: true

databases:
  - name: manga-recommender-db
    plan: free
    databaseName: manga_recommender
    user: manga_user